linters:
  disable-all: false
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gofmt
    - bodyclose
    - errname
    - errorlint
    - copyloopvar
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nilerr
    - nilnil
    - predeclared
    - stylecheck
    - thelper
    - tparallel
    - unparam
    - whitespace
    - staticcheck
    - govet
    - forcetypeassert
    - goconst
    #- gochecknoglobals
linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
