on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Check Commit
jobs:
  check_commit:
    name: Check Commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.0'
    - name: check
      run: make check
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.56.2
        only-new-issues: true
