on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Check Commit
jobs:
  check_commit:
    name: Check Commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.0'
    - name: install checkers
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/securego/gosec/v2/cmd/gosec@latest
    - name: check
      run: make check
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.2
        args: -E misspell
        only-new-issues: true
