on:
  push:
    branches:
      - master
    tags:
      - '*'
name: Build Docker Image
jobs:
  build_and_publish_docker_image:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: '[Dockerhub] Docker Login'
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
    - name: '[Github] Docker Login'
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: '${{ secrets.GH_DOCKER_PASSWORD }}'
        DOCKER_USERNAME: $GITHUB_ACTOR
        DOCKER_REGISTRY_URL: docker.pkg.github.com
    - name: Build kube-gen Image
      uses: actions/docker/cli@master
      with:
        args: build -t app .
    - name: '[Dockerhub] Tag Image'
      uses: actions/docker/tag@master
      with:
        args: --env app kylemcc/kube-gen
    - name: '[Github] Tag Image'
      uses: actions/docker/tag@master
      with:
        args: --env app docker.pkg.github.com/kylemcc/kube-gen/kube-gen
    - name: '[Dockerhub] Push Image'
      uses: actions/docker/cli@76ff57a
      with:
        args: push kylemcc/kube-gen
    - name: '[Github] Push Image'
      uses: actions/docker/cli@76ff57a
      with:
        args: push docker.pkg.github.com/kylemcc/kube-gen/kube-gen
    - name: Send Slack Notification
      uses: kylemcc/actions/slack-webhook@master
      if: always()
      env:
        SLACK_MESSAGE: '$GITHUB_REPOSITORY: $GITHUB_WORKFLOW ${{ job.status }}'
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
