on:
  push:
    branches:
      - master
    tags:
      - '*'
name: Build Docker Image
jobs:
  build_and_publish_docker_image:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: '[Dockerhub] Docker Login'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin
    - name: '[Github] Docker Login'
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u actions --password-stdin
    - name: Build and push image
      run: make push-image
    - name: Send Slack Notification
      uses: kylemcc/actions/slack-webhook@master
      if: always()
      env:
        SLACK_MESSAGE: '$GITHUB_REPOSITORY: $GITHUB_WORKFLOW ${{ job.status }}'
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
