on:
  push:
    tags:
      - v*
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.0'
    - id: tag-name
      run: |
        echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
    - run: |
        go install github.com/mitchellh/gox@latest
        make release
    - uses: docker://kylemcc/ghr:latest
      with:
        args: create -T ${{ steps.tag-name.outputs.TAG_NAME }} dist/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
